# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollen_counts', '0002_auto_20161028_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollencounts',
            name='datetime',
        ),
        migrations.AddField(
            model_name='pollencounts',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pollencounts',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
