# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollen_counts', '0004_auto_20161028_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollencounts',
            old_name='grass2',
            new_name='grass_2',
        ),
    ]
