# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollen_counts', '0003_auto_20161028_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollencounts',
            old_name='alder_count',
            new_name='alder',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='birch_count',
            new_name='birch',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='grass2_count',
            new_name='grass',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='grass_count',
            new_name='grass2',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='mold_count',
            new_name='mold',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='other1_count',
            new_name='other1',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='other1_tree_count',
            new_name='other1_tree',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='other2_count',
            new_name='other2',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='other2_tree__count',
            new_name='other2_tree',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='spruce_count',
            new_name='spruce',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='total_grass_count',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='total_pollen_count',
            new_name='total_pollen',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='total_tree_count',
            new_name='total_tree',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='weed_count',
            new_name='weed',
        ),
        migrations.RenameField(
            model_name='pollencounts',
            old_name='willow_count',
            new_name='willow',
        ),
    ]
